spring.application.name=devis
spring.datasource.url=jdbc:postgresql://192.168.1.5:5432/devis_db
spring.datasource.username=devis_user
spring.datasource.password=dev1sUs3r

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

## Cmd : mvn test -Dspring.profiles.active=test