# application-dev.properties — uniquement ce qui est spécifique au dev

spring.datasource.url=jdbc:postgresql://192.168.1.5:5432/devis_db
spring.datasource.username=devis_user
spring.datasource.password=dev1sUs3r


## Cmd : mvn spring-boot:run -Dspring-boot.run.profiles=dev